---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluxcoins5-hasher
  namespace: flux-system
spec:
  releaseName: hasher
  values: {}
  chart:
    spec:
      chart: generic-chart
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: helmcoins
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: fluxcoins5
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluxcoins5-redis
  namespace: flux-system
spec:
  releaseName: redis
  values:
    image:
      repository: redis
      tag: latest
    service:
      port: 6379
  chart:
    spec:
      chart: generic-chart
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: helmcoins
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: fluxcoins5
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluxcoins5-rng
  namespace: flux-system
spec:
  releaseName: rng
  values: {}
  chart:
    spec:
      chart: generic-chart
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: helmcoins
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: fluxcoins5
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluxcoins5-worker
  namespace: flux-system
spec:
  releaseName: worker
  values:
    service: false
  chart:
    spec:
      chart: generic-chart
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: helmcoins
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: fluxcoins5
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluxcoins5-webui
  namespace: flux-system
spec:
  releaseName: webui
  values:
    service:
      type: NodePort
  chart:
    spec:
      chart: generic-chart
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: helmcoins
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: fluxcoins5

