---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluxcoins5-hasher
  namespace: flux-system
spec:
  chart:
    spec:
      chart: generic-chart
      releaseName: hasher
      values: {}
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: helmcoins
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: fluxcoins5
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluxcoins5-redis
  namespace: flux-system
spec:
  chart:
    spec:
      chart: generic-chart
      releaseName: redis
      values:
        image:
          repository: redis
          tag: latest
        service:
          port: 6379
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: helmcoins
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: fluxcoins5
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluxcoins5-rng
  namespace: flux-system
spec:
  chart:
    spec:
      chart: generic-chart
      releaseName: rng
      values: {}
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: helmcoins
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: fluxcoins5
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluxcoins5-worker
  namespace: flux-system
spec:
  chart:
    spec:
      chart: generic-chart
      releaseName: worker
      values:
        service: false
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: helmcoins
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: fluxcoins5
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluxcoins5-webui
  namespace: flux-system
spec:
  chart:
    spec:
      chart: generic-chart
      releaseName: webui
      values:
        service:
          type: NodePort
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: helmcoins
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: fluxcoins5

