---
apiVersion: v1
kind: Namespace
metadata:
  name: fluxcoins3
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fluxcoins3
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./manifests/dockercoins
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: fluxcoins3
