---
apiVersion: v1
kind: Namespace
metadata:
  name: deployed-with-flux
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blue
  name: blue
  namespace: deployed-with-flux  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: blue
    spec:
      containers:
      - image: jpetazzo/color
        name: color
