apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- ../../../apps/blue/flux.yaml
- ../../../apps/fluxcoins1/flux.yaml
- ../../../apps/fluxcoins2/flux.yaml
- ../../../apps/fluxcoins3/flux.yaml
