---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: helmcoins
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/jpetazzo/2025-02-helmcoins
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluxcoins4
  namespace: flux-system
spec:
  chart:
    spec:
      chart: umbrella-chart
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: helmcoins
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: fluxcoins4
